WOF table Override file for 30BC Processor
open-power/everest-xml pull request #24
Opened 2024-01-29 20:40 UTC by adangster

This change is limited to FW1050.10 for a customer POC. And this change will not effect existing customer because this processor is not Generally Available.  Wof override bin tar file for 30BC processor sort for 1050.10 target.

2024-01-29 21:24 UTC, dcrowell77 requested changes
The file name has to exactly match the name of the mrw xml file, including the same case.  So the name has to be "Everest-MRW.WofSetBins.tar.gz"

2024-01-29 21:32 UTC, EricMarz commented
Verified that the WOF binary in Everest-MRW.WofSetBins.tar.gz is correct for this Everest 30BC specific override.

2024-01-30 16:10 UTC, dcrowell77 submitted a review, later dismissed

2024-01-30 20:56 UTC, adangster commented
Defect Opened
https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=595589

2024-04-30 17:38 UTC, merged